# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Klayton Smith/Desktop/ComputerHWDesignFinalProject/final-project-dash/final-project-dash.srcs/sources_1/ip/pixelclock/pixelclock.xci
# IP: The module: 'pixelclock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Klayton Smith/Desktop/ComputerHWDesignFinalProject/final-project-dash/final-project-dash.gen/sources_1/ip/pixelclock/pixelclock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelclock'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Klayton Smith/Desktop/ComputerHWDesignFinalProject/final-project-dash/final-project-dash.gen/sources_1/ip/pixelclock/pixelclock.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelclock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Klayton Smith/Desktop/ComputerHWDesignFinalProject/final-project-dash/final-project-dash.gen/sources_1/ip/pixelclock/pixelclock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelclock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Klayton Smith/Desktop/ComputerHWDesignFinalProject/final-project-dash/final-project-dash.srcs/sources_1/ip/pixelclock/pixelclock.xci
# IP: The module: 'pixelclock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Klayton Smith/Desktop/ComputerHWDesignFinalProject/final-project-dash/final-project-dash.gen/sources_1/ip/pixelclock/pixelclock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelclock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Klayton Smith/Desktop/ComputerHWDesignFinalProject/final-project-dash/final-project-dash.gen/sources_1/ip/pixelclock/pixelclock.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelclock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Klayton Smith/Desktop/ComputerHWDesignFinalProject/final-project-dash/final-project-dash.gen/sources_1/ip/pixelclock/pixelclock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pixelclock'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
